### ISSUE TITLE
The log2FC is not match with average of normalized raw counts values 

### ISSUE THREAD

**Issue by lida-R** [mikelove/DESeq2#101]
Hi there,

I have a experiment with one conditions and two factor A  vs  B
the Raw count values is :

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/LIDA~1.ZEI/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/LIDA~1.ZEI/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>

GeneName | A.Rep0 | A.Rep1 | A.Rep2 | A.Rep3 | A.Rep4 | A.Rep5 | A.Rep6 | A.Rep7 | A.Rep8 | A.Rep9 | A.Rep10 | A.Rep11 | B.Rep0 | B.Rep1 | B.Rep2 | B.Rep3 | B.Rep4 | B.Rep5 | B.Rep6 | B.Rep7 | B.Rep8 | B.Rep9 | B.Rep10 | B.Rep11
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
TNMD | 138 | 93 | 411 | 24 | 15 | 32 | 54 | 31 | 28 | 31 | 65 | 33 | 5082 | 32 | 9 | 293 | 6831 | 274 | 14 | 27 | 19 | 27 | 20 | 8

</body>

</html>

After I ran Deseq2 , I don't understand how the log2Fc was calculated for this gene. If I calculate log2(B.Mean/A.Mean) For most of the genes the values are close to log2FC which calculated by Deseq2 but for **"TNMD"** the value is very different !  "log2FC = 0.71236 , 
my log2foldchange = 3.964"

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/LIDA~1.ZEI/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/LIDA~1.ZEI/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>

GeneName | A.Mean | B.Mean | log2FC | pvalue | FDR |   | B/A | LOG2(B/A)
-- | -- | -- | -- | -- | -- | -- | -- | --
TSPAN6 | 1788.337292 | 1789.491618 | 0.001097 | 0.99059 | 0.997863 |   | 1.000645 | 0.000930922
**TNMD** | 69.51823529 | 1085.151163 | **0.712364** | 0.159306 | 0.55753 |   | 15.60959 | **3.964360755**
DPM1 | 822.2149057 | 818.4514789 | -0.00673 | 0.956658 | 0.990896 |   | 0.995423 | -0.006618636

</body>

</html>

Do you have any thoughts?

Thank you,
Lida

**Comment by mikelove** [comment]
This has been answered a number of times on the support site, can you look here.

Also please post there for future questions about software usage. Thanks!

https://www.google.com/search?client=firefox-b-1-d&q=site%3Asupport.bioconductor.org+deseq2+log2fc+average+normalized+counts
