### ISSUE TITLE
DESeq2 Vignette: Issue with pheatmap clustering distance measure

### ISSUE THREAD

**Issue by SuhasSrinivasan** [mikelove/DESeq2#102]
Dear Authors,

Thank you so much for developing and maintaining DESeq2!

There seems to be an issue with the following arguments for `pheatmap`

https://github.com/thelovelab/DESeq2/blob/4497a51ab22e86513ebaec930de3825b45fc89a4/vignettes/DESeq2.Rmd#L1410-L1411

```
Error in if (!(distance[1] %in% c("correlation", "euclidean", "maximum",  : 
  the condition has length > 1
> traceback()
2: cluster_mat(mat, distance = clustering_distance_rows, method = clustering_method)
1: pheatmap::pheatmap(sample_dist, clustering_distance_rows = sample_dist, 
       clustering_distance_cols = sample_dist, col = colors)
```

These parameters expect the distance measure and not the distance matrix.

Is it necessary to specify these arguments? 
Since the `dist(t(assay(vsd)))` call has default metric of `euclidean`.

**Comment by mikelove** [comment]
According to its man page

> clustering_distance_rows
distance measure used in clustering rows. Possible values are "correlation" for Pearson correlation and all the distances supported by dist, such as "euclidean", etc. If the value is none of the above it is assumed that a distance matrix is provided.

matrix should be allowed. Check the _class_ you are providing.
