### ISSUE TITLE
What defines a gene as "low counts [2]"

### ISSUE THREAD

**Issue by jamespblloyd-uwa** [mikelove/DESeq2#103]
Hello DESeq2 team, 

I was just wondering what defines a gene as low counts [2]. I see I get 15% of my genes here (3737), which probably makes sense, but I was just curious about the numerical way in which this threshold is made. Is it a flat counts < X? Is it that but related to length of gene? Or some more complex algorithm I will have no hope of understanding as a digital noob? 

```
> summary(res_Moss)

out of 24671 with nonzero total read count
adjusted p-value < 0.05
LFC > 0 (up)       : 7061, 29%
LFC < 0 (down)     : 6924, 28%
outliers [1]       : 4, 0.016%
low counts [2]     : 3737, 15%
(mean count < 2)
```

Thanks again for the wonderful tool. 
All the best, James

**Comment by mikelove** [comment]
The vignette talks about independent filtering, which is what is shown here with the note in [2] .

For more usage questions, usually we direct to support site and use GitHub more for code related Qs or bugs.
