### ISSUE TITLE
Pseudogenes with covariates

### ISSUE THREAD

**Issue by OlgaVT** [mikelove/DESeq2#104]
Hi!

I am running DESeq 2 for differential transcript analysis with and without covariates based on salmon outputs.

The part of the script without covariates:

```
dds <- DESeqDataSetFromTximport(txi, colData = sampleData, design = ~ condition)
dds <- DESeq(dds)

```
The part with covariates:
```
dds_cov <- DESeqDataSetFromTximport(txi, colData = sampleData, design = ~rin+age+batch+condition)
dds_cov <- DESeq(dds_cov)
```

For most of the transcripts, the results are quite similar (I saved them as csv files).

No covariates:
```
"","baseMean","log2FoldChange","lfcSE","stat","pvalue","padj"
"ENST00000264211",3691.93237827927,-0.342981522190213,0.151388569632226,-2.26557079588923,0.0234776748478348,0.613276642000467
```

Covariates:
`"ENST00000264211",3691.93237827927,-0.501338245827277,0.131061662877028,-3.82520894990987,0.000130661217811109,0.028712115547079`

But for pseudogenes, the baseMean differs greatly.

No covariates:
```
"","baseMean","log2FoldChange","lfcSE","stat","pvalue","padj"
"ENST00000427426",99.7100305986214,0.00404682837996939,0.32644988421097,0.0123964766896781,0.99010929596336,0.99999403158995
```

Covariates:
`"ENST00000427426",4598.3699521071,1.64690824374124,0.958059495749209,1.71900414436511,0.0856136172941855,0.636767921269823`

The same behaviour is for several other transcripts that belong to pseudogenes. Am I missing something? Thank you!

**Comment by mikelove** [comment]
For usage questions please post to support site.

For this one, it's likely the outlier treatment, which is influenced by the design.
