### ISSUE TITLE
Many DEGs (Is a high percentage of DEGs acceptable in DESeq2)?

### ISSUE THREAD

**Issue by vinadiscar** [mikelove/DESeq2#105]
Hi @mikelove 

I have this result:
```shell
> summary(res)

out of 60448 with nonzero total read count
adjusted p-value < 0.05
LFC > 0 (up)       : 7132, 12%
LFC < 0 (down)     : 6975, 12%
outliers [1]       : 751, 1.2%
low counts [2]     : 14064, 23%
(mean count < 3)
[1] see 'cooksCutoff' argument of ?results
[2] see 'independentFiltering' argument of ?results
```
Questions:
(1) There are many DEGs in this result. Is this percentage of upregulated (12%) and downregulated  (12%) genes acceptable in DESeq2 analysis? Does it not violate the usual result?

(2) Also, I observed that LFC > 0 and LFC < 0 automatically appeared in the result by default. As most studies use higher than 0, is this threshold acceptable? Could it be the reason why I am having many DEGs?

Thank you!

**Comment by mikelove** [comment]
Could you post to the support site for future usage questions?

1) this is not a violation of the size factor calculation. check plotPCA, likely the groups are separated well
2) see the 2014 paper, or the vignette or workflow, you can use `lfcThreshold` and we recommend it
