### ISSUE TITLE
Rlog - MDS plots

### ISSUE THREAD

**Issue by ReemaSingh** [mikelove/DESeq2#108]
Hi,

I apologize for posting my question as an issue. I have a question about using rlog with TMM normalized values. Specifically, I would like to generate an MDS plot in DESeq2 using TMM normalized values obtained from edgeR. My question is: Is it appropriate to apply rlog or vst transformations to TMM normalized values?
Any response would be appreciated.

Thank you,

**Comment by mikelove** [comment]
Usually these type of questions are best as support site posts

GitHub we mostly use for questions about DESeq2 lines of code 

I think edger has their own transformations, see ?cpm
