### ISSUE TITLE
Using full colData in plotPCA

### ISSUE THREAD

**Issue by assaron** [mikelove/DESeq2#109]
Hi Mike,

Is there any particular reason why `colData` is subset to the group column only for a ggplot object? I would like to modify the plot, for example to show donor with shape:

```r
dds <- makeExampleDESeqDataSet(betaSD=1)
colData(dds)$donor <- rep(paste0("donor", 1:6), 2)
vsd <- vst(dds, nsub=500)
plotPCA(vsd) + ggplot2::aes(shape=donor)
```
![image](https://github.com/user-attachments/assets/1134adfa-e20a-4014-9840-6b420bf39528)

It should be an easy fix:
```
diff --git a/R/plots.R b/R/plots.R
index 78840cb..591a45e 100644
--- a/R/plots.R
+++ b/R/plots.R
@@ -270,7 +270,7 @@ plotPCA.DESeqTransform = function(object, intgroup="condition",
   pcs <- paste0("PC", pcsToUse)
   d <- data.frame(V1=pca$x[,pcsToUse[1]],
                   V2=pca$x[,pcsToUse[2]],
-                  group=group, intgroup.df, name=colnames(object))
+                  group=group, name=colnames(object), colData(object))
   colnames(d)[1:2] <- pcs
   
   if (returnData) {
```

**Comment by mikelove** [comment]
You can just add everything you like to use with intgroup and then customize your own plot with ggplot2, no?

**Comment by assaron** [comment]
Technically I could, but I'd need to include the fields both to intgroup and to ggplot2 modifiers: `plotPCA(vsd, intgroup=c("condition", "donor")) + ggplot2::aes(color=condition, shape=donor)`. I feel it to be too redundant, while using all of the columns is much more streamlined. And I don't see any downsides of that.

**Comment by mikelove** [comment]
Can you try out 29161e7 ?

Thanks for the suggestion

**Comment by assaron** [comment]
It works perfectly, thanks!

**Comment by mikelove** [comment]
cool, good suggestion -- i'll push to Bioc devel branch

**Comment by mikelove** [comment]
credit [30cc350](https://github.com/thelovelab/DESeq2/commit/30cc350d58c307a2c564c2b372ec2a50462a8097)
