### ISSUE TITLE
lfcshrink "lessAbs" returns "greaterAbs"

### ISSUE THREAD

**Issue by Froblinkin** [mikelove/DESeq2#19]
This contrasts with the expected behavior when one calls the results method, which lfcshrink is built onto of.

**Expected:**
![expected_bh](https://user-images.githubusercontent.com/12719005/73111668-38345300-3ed9-11ea-931c-fbf0592a496b.png)

**Reality:**
![reality_lfcshrink](https://user-images.githubusercontent.com/12719005/73111674-3d919d80-3ed9-11ea-862a-7fea4e820b13.png)

**Comment by mikelove** [comment]
The argument isn’t being used- lfcShrink doesn’t have altHypothesis as an argument, and then it passes extra args to other packages. The way R handles the “...” means it doesn’t give an error when you add an argument that a function doesn’t have.
