### ISSUE TITLE
ashr removed from CRAN

### ISSUE THREAD

**Issue by mjsteinbaugh** [mikelove/DESeq2#20]
Hi @mikelove , looks like you're already aware of this, but I see that ashr was removed from CRAN recently: https://cran.r-project.org/web/packages/ashr/index.html

I see some changes in DESeq2 that appear to reflect this, but I wanted to post in case other users hit this issue: https://github.com/mikelove/DESeq2/commit/6a4d125a18abd57dc3b3e4f0624c6eac8fa71506

**Comment by mikelove** [comment]
Thanks - yeah the devel branch of DESeq2 has been modified temporarily to not Suggest ashr. However, it’s my understanding that ashr will be showing up again on CRAN soon as the dependency is already up.

**Comment by mjsteinbaugh** [comment]
That's what I figured. I hit a similar issue with Matrix.utils a few days ago and had to update a bunch of my single-cell code.
