### ISSUE TITLE
Error with SummarizedExperiment 1.17.2

### ISSUE THREAD

**Issue by mdeber** [mikelove/DESeq2#21]
Hi, the development version of SummarizedExperiment (1.17.2, 20-02-14) is causing a new error (below). I'm on Bioc 3.11 (and R devel 2020-01-10 r77651) and DESeq2 1.27.24. Rolling back to SummarizedExperiment 1.16.1 (latest official release) fixed the problem. 

```
error: (unknown)
please use 'assay(x, withDimnames=FALSE)) <- value' or 'assays(x,
  withDimnames=FALSE)) <- value' when the dimnames on the supplied
  assay(s) are not identical to the dimnames on DESeqDataSet object 'x'

Backtrace:
  ...
  7. DESeq2::estimateDispersions(...)
  8. DESeq2:::.local(object, ...)
  9. DESeq2::estimateDispersionsGeneEst(...)
 11. SummarizedExperiment::`assays<-`(`*tmp*`, value = `*vtmp*`)
```

**Comment by mikelove** [comment]
I saw this today on the Bioc build pages, but when I updated packages on my computer to devel latest, I couldn't reproduce the problem with R CMD check on my end.

I'm waiting to see if it continues (and I have to adjust code) or if it was a fluke.

**Comment by mikelove** [comment]
I can reproduce the error today for some reason. I'll fix asap.

**Comment by mikelove** [comment]
Just pushed 1.27.25 to devel which should resolve this (it will be taken up today at 5pm and if resolved will clear the ERROR msg on Bioc by Friday).
