### ISSUE TITLE
Result interpretation 

### ISSUE THREAD

**Issue by OmonkeyGOD** [mikelove/DESeq2#22]
Hi, 
Thanks for developing this useful package.
I have a question about the results of DESeq2. Usually, I use q-value<=0.05 and |FC|>2 as the criteria to screen differentially expressed genes. If I want to identify genes with similar expression under different conditions, which criteria should I use? I was thinking of only using q-value>0.05. But there are also some genes with |FC|~1 and q-value<=0.05. 
Thank you very much!

**Comment by mikelove** [comment]
Please post support questions here:

https://support.bioconductor.org

Thanks!
