### ISSUE TITLE
Why DESeq2 do not support the decimals for count matrix

### ISSUE THREAD

**Issue by DustinChen1986** [mikelove/DESeq2#23]
I prepare a count matrix from the salmon results, but DESeq2 do not support this. While the documentation of tximport provides poor explainations for many steps and  parameters.

**Comment by mikelove** [comment]
We have a function for tximport to DESeq2. See the vignette, and please post future questions to Bioc support site.

**Comment by DustinChen1986** [comment]
Thank you for your advice. Bioc support site is a good platform I did not find it before.  After painfully  attempts, I can understand the tximport command and transmit the salmon results to DESeq2 successfully yesterday.
