### ISSUE TITLE
plotCounts Scaling Definitions

### ISSUE THREAD

**Issue by DarioS** [mikelove/DESeq2#31]
In the function documentation is "normalized by size factor" but in the vignette "normalizes counts by sequencing depth". These two could mean the same but might not. I would like to see the function's documentation explicitly define what is meant by size factor. `estimateSizeFactors` has three different approaches to calculate the factors, so this could be more precisely defined.

**Comment by mikelove** [comment]
Good point, I'll fix the vignette sentence.

**Comment by mikelove** [comment]
Ok I've changed it to mention that it uses size factor (or normalization factor if these were used).

73609c9
