### ISSUE TITLE
Inconsistent naming of interaction terms in some cases

### ISSUE THREAD

**Issue by frederikziebell** [mikelove/DESeq2#39]
Hi Mike,

I noticed when doing spline fitting that for some designs the naming of the interaction terms is inconsistent. In this example

```
library("fission")
library("splines")
data("fission")

dds <- DESeqDataSet(fission, design=~1)
dds$minute <- as.double(dds$minute)
spline_basis <- ns(dds$minute, df=3)
colnames(spline_basis) <- paste0("spline",colnames(spline_basis))
colData(dds) <- cbind(colData(dds), spline_basis)

design(dds) <- ~spline1:strain + spline2:strain + spline3:strain
dds <- DESeq(dds, test="LRT", reduced=~spline1 + spline2 + spline3, parallel=T)
colnames(mcols(dds))
```

the interaction terms are named `spline1.strainwt`,  `spline1.strainmut`, `strainwt.spline2`, `strainmut.spline2`, `strainwt.spline3`, and `strainmut.spline3`.

I know that this is not the best full design to interpret, but it's the simplest case I could find. In contrast, chainging the design to ` ~spline1 + spline2 + spline3 + spline1:strain + spline2:strain + spline3:strain` gives consistent names.

**Comment by mikelove** [comment]
These terms are named by R's `model.matrix` not DESeq2. So I think I can't help you here.

**Comment by frederikziebell** [comment]
Thanks, I thought that was due to some internal parsing, like replacing ":" with ".". Didn't have `model.matrix` on my radar.
