### ISSUE TITLE
Inconsistent contrast names 

### ISSUE THREAD

**Issue by bomquangia** [mikelove/DESeq2#41]
Hi, 

I am trying to use DESeq2 for single cell RNA data, and following  DESeq2 Vignette recommendation to use `LRT` test and `glmGamPoi`. Yet I notice some inconsistencies in the naming of contrast while running the `DESeq` function with and without parallelization as shown below. To my understanding, no matter the statistical tests used and parallelization, the contrast terms should be similarly named, isn't it?

Another problem is that when I run without parallelization, the resulting logFC could not be shrinked with `apeglm` and when I inspect the each contrast result before shrinkage,  all `lfcSE` value is NA. Again, I don't think parallelization should have had any effect here. 

I am using DESeq2 1.31.18, GithubSHA1:  a5941b305b597556d47c68df0b922a0a20b41fb6.

Would love to here your opinion on this.

Best regards,
Vu

Without parallelization
```
dds1 <- DESeq2::DESeq(dds1, test="LRT", 
                        reduced=as.formula(arg$options$reduced_formula),
                        minmu=1e-6, minRep=Inf, 
                        betaPrior = FALSE,
                        quiet=FALSE,
                        fitType='glmGamPoi')
```

![image](https://user-images.githubusercontent.com/16002603/119803693-e014c300-bf09-11eb-953e-9f6bb35ff9e6.png)

Wth Parallelization
  ```
dds1 <- DESeq2::DESeq(dds1, test="LRT", 
                        reduced=as.formula(arg$options$reduced_formula),
                        minmu=1e-6, minRep=Inf, 
                        betaPrior = FALSE,
                        quiet=FALSE,
                        useT=TRUE, BPPARAM=param.opt, parallel=TRUE,
                        fitType='glmGamPoi')
```
![image](https://user-images.githubusercontent.com/16002603/119803976-210cd780-bf0a-11eb-8310-320dc8ab6eea.png)

Identical `dds1` object but with `test ='Wald'`
![image](https://user-images.githubusercontent.com/16002603/119804239-5d403800-bf0a-11eb-9c04-be2f7b268079.png)

**Comment by mikelove** [comment]
The glmGamPoi-implementation code in DESeq2 was written by @const-ae but from my understanding, it does not work with `parallel=TRUE`. I think we should add a warning() when both options are chosen. What is happening is that you are using standard DESeq2 estimation for most steps (so slower for large sample size), except for a re-implementation of the trend in the `estimateDispersionsFit` step (which is anyway the fastest step, so you aren't gaining the improvement).

By the way, to avoid adding figures, you can use triple backticks to add code blocks with copy-paste.

**Comment by bomquangia** [comment]
But that still does not answer the problem of why there is `glmGamPoi` and no parallelization, the name of the returned contrast is different? And the entire lfcSE column is `NA`?

**Comment by mikelove** [comment]
Oh, that is because glmGamPoi has a different mechanism, and avoids changing the column names. It also does not compute SE for LFC.

**Comment by bomquangia** [comment]
Oh I see. Thanks for your swift response!

**Comment by mikelove** [comment]
Thanks for your report, I've added this warning now: e692ae6
