### ISSUE TITLE
plotPCA Question

### ISSUE THREAD

**Issue by nadeaue** [mikelove/DESeq2#47]
Hi there. I'm trying to get the loadings on the PCA I make with the plotPCA function after I run DESeq. I haven't been able to find anything about this process in the manuals or vignettes.

**Comment by mikelove** [comment]
You cannot obtain the loadings with this helper function, I recommend to use the internal code:

https://github.com/mikelove/DESeq2/blob/master/R/plots.R#L217-L226

From the last line highlighted you can obtain all the parts of the decomposition.
