### ISSUE TITLE
How to get DESeq2 results in large count matix files?

### ISSUE THREAD

**Issue by mathavanpu** [mikelove/DESeq2#48]
Dear All
I am working on a denovo transcriptome analysis of the sugar cane plant. The count matrix has a **1792064** number of transcripts. Now, the differential gene expression is running by the tools DESeq2. The total number of samples is **36** and it has **12** groups comparison. The differential gene expression has been running for more than **25** days to date. Some files are generated in the data folder

readCountRlogNorm.xls
rlog_Normalized_Values.txt
readCountNorm.xls

and the figure folder
SampleDistanceRlog.pdf
SampleCorrelationRlog.pdf
PCA.png

absPairVenn folder showing empty

Please check the library used in the script.
library(DESeq2)
library("BiocParallel")
register(MulticoreParam(100))

Command used
Rscript DEseq2_replicate.R counts.matrix SampleInfo_Replicates contrast 

Please help me!!!

**Comment by mikelove** [comment]
Two notes, the slowdown here is likely mostly from the number of cores not DESeq2. Sending data across many cores is often the slowest step, and using 10 cores requested on the same node is much faster than asking for 100 cores distributed across a network.

But for faster inference, you should use fitType=“glmGamPoi” — you can call this from DESeq().

**Comment by mikelove** [comment]
Here's an example for timing. Consider 10,000 features -- by the way, you should definitely be filtering for _expressed transcripts_ at the beginning of the script, as in:

```
keep <- rowSums(counts(dds) >= 10) >= X
```

Where you may want X to be 3 samples or even more, depending on the nature of the experiment.

But then for multicore or for glmGamPoi, 10,000 features are tested across 12 groups of samples, with 36 total in this script:

```
library(DESeq2)                                                                                                                                                                               
library(glmGamPoi)                                                                                                                                                                            
dds <- makeExampleDESeqDataSet(n=10000,m=36)                                                                                                                                                  
dds$condition <- factor(rep(1:12,each=3))                                                                                                                                                     
library(BiocParallel)                                                                                                                                                                         
bp <- MulticoreParam(4)                                                                                                                                                                       
system.time({                                                                                                                                                                                 
  dds2 <- DESeq(dds, BPPARAM=bp)                                                                                                                                                              
})                                                                                                                                                                                            
system.time({                                                                                                                                                                                 
  dds2 <- DESeq(dds, fitType="glmGamPoi", reduced=~1, test="LRT")                                                                                                                             
})
```

On a laptop with 4 cores, the multicore version on 10k features takes about 21 seconds, while glmGamPoi takes about 9.5 seconds.

I don't know how many unique expressed features there are in your plant example, but there may be many transcripts with nearly identical sequence, and you would benefit from grouping these together for testing: 

https://doi.org/10.1093/bioinformatics/btaa448

Let's say there are 100k expressed features, after filtering out transcripts that are lowly expressed and grouping nearly identical features. Then DESeq2 should take less than 5 minutes.
