### ISSUE TITLE
DESeq2 Ignore Some Significant Differential Genes due to Extreme Count Outlier 

### ISSUE THREAD

**Issue by ijayden-lung** [mikelove/DESeq2#5]
or example, the read count of gene Z in condition A is 0, 0, 0, 123 and in condition B is 13000,13500,12500,14000. It is obvious that gene Z is significantly differential express between condition A and condition B, however, sometimes, DESeq2 set the pvalue to NA because of the outlier in condition A. 

I suggest that before filtering the outliers, firstly testing whether the maximum value in condition A  is far less than the minimum value in condition B. To do this, DESeq2 can reduce the false negative rate.

**Comment by mikelove** [comment]
Thanks
