### ISSUE TITLE
weired dispersion and mean

### ISSUE THREAD

**Issue by wangjiawen2013** [mikelove/DESeq2#51]
Hi,
I am using DESeq2 to process my RNAseq data, it looks like there are something wrong with my data, here is the 
Is the diagnostic plot right ? what does "mean of normalized counts" ? I have read the DESeq2 paper, however I don't quite understand it, and what kind of diagnostic plot is good ?

**Comment by mikelove** [comment]
Can we switch to support site where you can post images? Have you seen the vignette? The `baseMean` is described there, and some example plots are shown.
