### ISSUE TITLE
Can DESeq2 deal with comparison between different species?

### ISSUE THREAD

**Issue by gouwei1** [mikelove/DESeq2#52]
Dear Michael,

I want to compare the gene expression between different species, using orthogroup ID to connnect their gene ID. Can DESeq2 deal with that?

Yours,
Wei

**Comment by mikelove** [comment]
It can be done but requires extra consideration, see the threads on the
support site.

**Comment by gouwei1** [comment]
Thanks for you reply, but I can not find the messages about that at http://www.bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html. Could you tell me where's the support site?

**Comment by mikelove** [comment]
See the vignette Abstract

**Comment by mikelove** [comment]
This is where you should go for Bioconductor support:

https://support.bioconductor.org

You can use google to search Bioconductor support site threads:

https://www.google.com/search?q=site%3Asupport.bioconductor.org+deseq2+species

**Comment by gouwei1** [comment]
That's very helpful. Thank you Michael.
