### ISSUE TITLE
About normalized counts of DESeq2

### ISSUE THREAD

**Issue by gouwei1** [mikelove/DESeq2#54]
Hi,

I want to select a control gene in Real-time qPCR analysis, such as beta-actin. But I found it is a multiple copy gene in my studies species, and I compared their TPM abundance, finding their expression level are not stable. Later I thought maybe TPM value is not proper to judge that, because TPM is more like a proportion of a gene in all expressed genes. And later I found the normalization of DESeq2 is different. The normalized count were obtained by using :

dds <- DESeq(dds)
normalized_counts <- counts(dds, normalized=TRUE)

I though this normalized method can be more correct to obtain a real expression level, while the counts of beta-actin are still not stable. Maybe it's a real situation, or maybe this method can not be applied to do that? Could you tell me the answer ?

Best,
Wei

**Comment by mikelove** [comment]
I don’t think DESeq2 helps here, the relative expression level is best measured with TPM. Absolute expression level requires controls or strong assumptions about housekeeping genes. Counts are useful for testing but not for measuring abundance.
