### ISSUE TITLE
vst blind

### ISSUE THREAD

**Issue by igordot** [mikelove/DESeq2#56]
I think this might be considered a documentation issue.

In the `vst()` description, it states:

> This wrapper for the VST is not blind to the experimental design: the sample covariate information is used to estimate the global trend of genes’ dispersion values over the genes’ mean normalized count. It can be made strictly blind to experimental design by first assigning a design of ~1 before running this function

However, `vst()` has the `blind` parameter (`TRUE` by default) with the description:

> whether to blind the transformation to the experimental design (see varianceStabilizingTransformation)

Those sound somewhat contradictory. If the function is not blind, then what is the purpose of the `blind` parameter?

**Comment by mikelove** [comment]
Thanks, the docs were just out of date, it is in fact blind by default and can be simply adjusted with the argument:

[37fad26](https://github.com/mikelove/DESeq2/commit/37fad26636ba0d3582017f1bae318eca91461d95)
