### ISSUE TITLE
MeanSD plot

### ISSUE THREAD

**Issue by L3ft2di3** [mikelove/DESeq2#60]
Hey,

Since recently, I observed a problem with the meanSD plot function originating from the vsn package. My plot looks exactly like one linked to a very recent report of yours: http://bioconductor.org/packages/devel/bioc/vignettes/DESeq2/inst/doc/DESeq2.html
which I found via the google images search. It was published 18h ago, although by now the plots in the html manual on the DESeq2 bioconductor site look okay again. How did you fix that issue?
Would greatly appreciate a tip.

Thank you in advance!

**Comment by mikelove** [comment]
I'm not sure, I didn't make any changes and am not behind the *vsn* package. I'm taking a look at the code though.

**Comment by mikelove** [comment]
Just posting a picture and a link:

http://bioconductor.org/packages/devel/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#effects-of-transformations-on-the-variance

<img width="484" alt="Screen Shot 2022-11-15 at 4 07 57 PM" src="https://user-images.githubusercontent.com/69203/202025580-9a91e713-6e1d-4a0a-8a9b-a79f4a67e785.png">

**Comment by L3ft2di3** [comment]
Oh yeah, I guess I could have attached a picture as well.

I know that you are not the author of the vsn package, but thought you might have figured it out. Coudn't find a quick contact information on Wolfang Huber, the vsn package author.
Thank you anyway.

**Comment by mikelove** [comment]
Looks fine in my R, but this is from June:

```
> x <- matrix(rnorm(10000*10,rep(rnorm(10000),10),rep(exp(rnorm(10000,0,.5)),10)),byrow=TRUE, ncol=10)
> meanSdPlot(x, rank=FALSE)
> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur ... 10.16
...
[1] vsn_3.65.0
```

<img width="689" alt="Screen Shot 2022-11-15 at 4 42 13 PM" src="https://user-images.githubusercontent.com/69203/202031178-ee6f96a7-6803-4fbe-9fc7-b9fe99e61196.png">

**Comment by L3ft2di3** [comment]
Interesting. Same code leads to this plot in my R:

![image](https://user-images.githubusercontent.com/75676504/202032360-51455079-d67c-493c-8e38-46abaed75055.png)

sessionInfo()
R version 4.2.2 (2022-10-31)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.6
..
vsn_3.66.0

**Comment by L3ft2di3** [comment]
Hey Mike,
did you hear anything from Wolfgang Huber?

**Comment by mikelove** [comment]
Not yet, but I haven't had a chance to update my R/Bioc to 3.16 yet. I hope to do that this week. Sorry for the delay.

**Comment by L3ft2di3** [comment]
No worries! Just curious and still wondering why this issue occurs.

**Comment by mikelove** [comment]
Let's see if we can work this out from the source, if you have a chance, try this function:

https://gist.github.com/mikelove/0a3c19a8512fb36453078df48f20d283

**Comment by L3ft2di3** [comment]
Update: I don't really know what fixed it, but I recently updated XQuartz on my mac and installed the new RStudio version. The plots now look as they used to.

@mikelove Thank you for you help anyway, really appreciate the support!

Cheers
Thorben
