### ISSUE TITLE
Archive 'many samples' tweetorial

### ISSUE THREAD

**Issue by frederikziebell** [mikelove/DESeq2#61]
Hi Mike,

since it's not clear atm how long Twitter will be around, maybe it's good to archive the really helpful tweetorial you mention in the _experiments with many samples_ section in the DESeq2 vignette. I've made a standalone html page of it [here](https://htmlpreview.github.io/?https://github.com/frederikziebell/science_tweetorials/blob/master/DESeq2_many_samples.html). Feel free to copy it to this repo.

Best,
Frederik

**Comment by mikelove** [comment]
That's fantastic Frederik. Thanks again. I'll change the vignette to point here.
