### ISSUE TITLE
Normalization of RNA seq data before DESeq2

### ISSUE THREAD

**Issue by Mercilena** [mikelove/DESeq2#68]
i have a dataset having 4 rna seq healthy tissue samples prepared with unstranded Illumina library and another dataset with 8 rna seq healthy tissue samples prepared with reverse stranded Illumina library. I wish to combine these 2 datasets together and run DGE with a third dataset having 100 tumor tissue samples. But DESEQ2 takes in raw counts as input. Can I normalize each dataset seaprately and then merge them together to run DESeq2?

**Comment by mikelove** [comment]
Please post support questions to the support site (on Bioc website). Thanks!
