### ISSUE TITLE
recover from failed zinbwave weights

### ISSUE THREAD

**Issue by roryk** [mikelove/DESeq2#7]
Hi Mike,

I have a dataset where a single gene fails the weight check in `getAndCheckWeights` when using zinbwave. I just removed it, but would you take a pull request where it automatically removes those genes from the object and moves on, rather than failing?

**Comment by mikelove** [comment]
hmm, i'd incline to not do that exactly (although still find a better solution), because all the functions in DESeq2 return all the genes

BTW what do the weights look like that fail the test?

another option would be to NA out the pvalues/padj for that gene and add a logical column to mcols(dds) that points to which genes didn't pass the test?

**Comment by roryk** [comment]
Great, that makes sense to me.

I stuck the entire DESeqDataSet object up here: https://www.dropbox.com/s/nbo34tuthh4i9dw/zinb-weight-fail.rda?dl=1 so you can see the model.matrix being used as well.

The failing gene is "2310057J18Rik".

**Comment by mikelove** [comment]
Ok, downloaded (in case you want to delete).

**Comment by mikelove** [comment]
So it makes sense why to give an error on this gene, there is no weight to any of the samples in the other groups, so comparisons won't be possible:

```
> wts <- pmax(assays(dds)[["weights"]]["2310057J18Rik",], 1e-6)
> tapply(wts, dds$condition, range)
$aaa
[1] 1e-06 1e-06

$bbb
[1] 1e-06 1e+00

$ccc
[1] 1e-06 1e-06

$ddd
[1] 1e-06 1e-06

$eee
[1] 1e-06 1e-06

$fff
[1] 1e-06 1e-06
```

**Comment by roryk** [comment]
haha-- I was literally just about to push a fix for this, sans tests and nice warning, good timing. Sure thing, will test now.

**Comment by roryk** [comment]
Awesome, looks good to me. Thanks so much MIke!

**Comment by mikelove** [comment]
thanks for identifying this. much better usability now
