### ISSUE TITLE
issue with installing the package on Apple M1 Max

### ISSUE THREAD

**Issue by sophieastrof** [mikelove/DESeq2#70]
Hi!
I get the following error when installing DESeq2 on my mac (M1 Max):

ld: warning: directory not found for option '-L/opt/R/arm64/gfortran/lib/gcc/aarch64-apple-darwin20.6.0/12.0.1'
ld: warning: directory not found for option '-L/opt/R/arm64/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [DESeq2.so] Error 1
ERROR: compilation failed for package ‘DESeq2’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/DESeq2’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/3j/r82js80x57zcctgt9fnzs9fc0000gp/T//RtmpB1ivha/filed39748a058c/DESeq2_1.39.8.tar.gz’ had non-zero exit status
> library(DESeq2)
Error in library(DESeq2) : there is no package called ‘DESeq2’

Thanks!
Sophie

**Comment by mikelove** [comment]
For Mac, I recommend using the M1 binaries. If you install the latest version of R, you can get Bioconductor binaries with BiocManager.

**Comment by sophieastrof** [comment]
Thanks so much for the quick reply! It worked.

From: Mike Love ***@***.***>
Date: Monday, April 24, 2023 at 1:05 PM
To: mikelove/DESeq2 ***@***.***>
Cc: Sophie Astrof ***@***.***>, Author ***@***.***>
Subject: Re: [mikelove/DESeq2] issue with installing the package on Apple M1 Max (Issue #70)

For Mac, I recommend using the M1 binaries. If you install the latest version of R, you can get Bioconductor binaries with BiocManager.
