### ISSUE TITLE
lfcShrink error

### ISSUE THREAD

**Issue by mmparedes5** [mikelove/DESeq2#71]
Hi, I'm following the DESeq manual. In the section of lfcShrink, I used de command:

```r
resLFC <- lfcShrink(dds, coef= "condition_carcinoma_vs_normal", type="apeglm")
``` 
but the result was the next error

```
Error in optimHess(par = init, fn = nbinomFn, gr = nbinomGr, x = x, y = y,  : 
  non-finite value supplied by optim
```

**Comment by mikelove** [comment]
I can’t tell from this post but you can likely just use ashr here.

**Comment by mikelove** [comment]
Feel free to continue on Bioc support
