### ISSUE TITLE
Unexpected behaviour from results(contrast) argument

### ISSUE THREAD

**Issue by JCSzamosi** [mikelove/DESeq2#72]
I have never seen this before and I am confused. I'm hoping someone can help. I have a single predictor variable, `Outcome` with two levels, `Responder` and `Non.responder`.

I am at a loss to explain this:

```
> resultsNames(dds)

 [1] "Intercept"                          "Outcome_Responder_vs_Non.responder" 

> res = results(dds, contrast = c('Outcome','Responder', 'Non.responder')) 

Error in cleanContrast(object, contrast, expanded = isExpanded, listValues = listValues,  :    Responder and Non.responder should be levels of Outcome such that Outcome_Responder_vs_Non.responder and Outcome_Non.responder_vs_Non.responder are contained in 'resultsNames(object)'
--
>
```
OTOH, specifying `name` works:

```
> res2 = results(dds, name = 'Outcome_Responder_vs_Non.responder')
>
```

Has something changed in how the `contrast` argument is specified that I'm not understanding? Am I missing something very obvious?

**Comment by mikelove** [comment]
Try not using symbols in the levels (from the beginning). Hyphens in particular are a problem for levels, if that’s what’s happening…

**Comment by JCSzamosi** [comment]
It was a space. And yes, that fixed it. I was assuming DESeq2 did the conversion from bad character to period once and then it would be fine, but I guess it's more complicated than that!

Thank you!
