### ISSUE TITLE
Significance testing with multi-condition single cell data: LRT, Wald test, or both?

### ISSUE THREAD

**Issue by mariecrane** [mikelove/DESeq2#76]
I have a large single cell dataset with 6 conditions, and I am struggling to determine what the appropriate significance test would be for differential gene expression between groups. Based on your [recommendations for single cell analysis](http://bioconductor.org/packages/devel/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#recommendations-for-single-cell-analysis), the log ratio test is more appropriate than the Wald test, but what if I want to test for pairwise differences between my conditions? I see in the results help page that it's possible to specify `test="Wald"` after running `nbinomLRT` to generate Wald statistics and Wald test p-values for individual contrasts. Would this be appropriate for single cell data though? Also, I'm just kind of confused about what is happening when I run `DESeq` with` test="LRT"` and `results` with `test="Wald"` -- which test will the resulting p-values come from? If they are Wald p-values, then why are they different from just running the whole pipeline with `test="Wald"`? Thank you in advance for your guidance.

**Comment by mikelove** [comment]
Would you mind posting this on https://support.bioconductor.org instead? That's my preferred site for taking these types of queries.

**Comment by mariecrane** [comment]
I saw that you prefer these types of questions on bioconductor but unfortunately I don’t have an account and the site won’t allow new sign ups at the moment (I’m not sure how soon this will be resolved). If you’d be willing to answer here, I would very much appreciate it, but I understand if not and will keep checking bioconductor to see if I can log in and post this question there

**Comment by mikelove** [comment]
Ok will do here

For LRT you can fit the dispersions (estimateSizeFactors then estimateDispersions) and then run nbinomLRT with different reduced matrices. These can be formed by removing columns of the full matrix that correspond to comparisons of two groups.

**Comment by mariecrane** [comment]
Thank you so much, I will try that!

I guess I am still wondering what happens when you run `nbinomLRT` and then specify `test="Wald"` in the `results` function? Are the resulting p-values just from a Wald test for the specified contrast or are they taking the results from the likelihood ratio test into account somehow? I'm struggling to understand why the resulting p-values from `nbinomLRT` followed by `results(test = "Wald")` are different from the p-values I get when running `nbinomWald` followed by `results(test="Wald")`.

**Comment by mikelove** [comment]
It should be essentially the same to do nbinomLRT -> results with Wald, and then nbinomWaldTest -> results. The only difference is that nbinomLRT fits two GLM which you don't need to do if you are going to do a Wald test that just uses estimated beta and its estimated covariance.

**Comment by mariecrane** [comment]
Got it, thanks so much!
