### ISSUE TITLE
error in saving up and down regulated genes 

### ISSUE THREAD

**Issue by SREESHMARAJ659** [mikelove/DESeq2#77]
Hello, 
I am using DESeq2 for differential expression analysis. Now i wanted to collect up and down regulated genes from the result. For that iam using the command 

RESULT <- res[which(res$pvalue<0.05) & abs(res$log2FoldChange > 1.5),]
write.table(RESULT, file = "upregulated.txt")

and  when i check the file it is not contain exact result. The upregulated.txt includes the genes which have p value 0.2, 0.4 etc. But i only need the genes which pvalue is less than 0.05 and lgfc greaterthan 1.5.
which command will be helpfull to collect genes according to this condition. 
Thank you in adavance.

**Comment by mikelove** [comment]
Can you post with a reproducible example to the support site on Bioconductor website?

Eg using makeExampleDESeqDataSet()

**Comment by SREESHMARAJ659** [comment]
I have a data set with 565561 rows and 9 coulmns.
 this is my results after performing   `dds <- DESeq(dds)` 

log2 fold change (MLE): condition leaf vs root 
Wald test p-value: condition leaf vs root 
DataFrame with 6 rows and 6 columns
                                                        baseMean log2FoldChange
                                                       <numeric>      <numeric>
TRINITY_DN29823_c1_g1_i1^RS18_ARATH^Ribosomal_S13      14.392892      -8.003800
TRINITY_DN27431_c0_g1_i11^DPB_ARATH                     7.621357      -0.805158
TRINITY_DN588067_c0_g1_i1^ILV5_NEUCR^IlvC               2.422774      -4.390179
TRINITY_DN249839_c0_g1_i1^MYB52_ARATH^Myb_DNA-binding  64.405562      -9.145858
TRINITY_DN316_c0_g2_i1^Y4374_ARATH                    775.703937       0.707842
TRINITY_DN476390_c0_g1_i1^BH049_ARATH                   0.545403       3.041497
                                                          lfcSE      stat
                                                      <numeric> <numeric>
TRINITY_DN29823_c1_g1_i1^RS18_ARATH^Ribosomal_S13      1.328289 -6.025649
TRINITY_DN27431_c0_g1_i11^DPB_ARATH                    0.665949 -1.209039
TRINITY_DN588067_c0_g1_i1^ILV5_NEUCR^IlvC              3.644055 -1.204751
TRINITY_DN249839_c0_g1_i1^MYB52_ARATH^Myb_DNA-binding  1.239868 -7.376478
TRINITY_DN316_c0_g2_i1^Y4374_ARATH                     0.303988  2.328519
TRINITY_DN476390_c0_g1_i1^BH049_ARATH                  3.971566  0.765818
                                                           pvalue        padj
                                                        <numeric>   <numeric>
TRINITY_DN29823_c1_g1_i1^RS18_ARATH^Ribosomal_S13     1.68433e-09 2.53820e-08
TRINITY_DN27431_c0_g1_i11^DPB_ARATH                   2.26648e-01 3.14645e-01
TRINITY_DN588067_c0_g1_i1^ILV5_NEUCR^IlvC             2.28299e-01 3.16516e-01
TRINITY_DN249839_c0_g1_i1^MYB52_ARATH^Myb_DNA-binding 1.62532e-13 4.67528e-12
TRINITY_DN316_c0_g2_i1^Y4374_ARATH                    1.98846e-02 4.35735e-02
TRINITY_DN476390_c0_g1_i1^BH049_ARATH                 4.43785e-01          NA


i wnated to collect the gwenes which have p value < 0.05 and log2foldchange >1.5
so i did 
`RESULT <- res[which(res$pvalue<0.05) & abs(res$log2FoldChange > 1.5),]`

but i got theresult 


<!DOCTYPE html>

<html>
<head>
	
	
	<title></title>
	<meta name="generator" content="LibreOffice 7.3.7.2 (Linux)"/>
	<style type="text/css">
		body,div,table,thead,tbody,tfoot,tr,th,td,p { font-family:"Liberation Sans"; font-size:x-small }
		a.comment-indicator:hover + comment { background:#ffd; position:absolute; display:block; border:1px solid black; padding:0.5em;  } 
		a.comment-indicator { background:red; display:inline-block; border:1px solid black; width:0.5em; height:0.5em;  } 
		comment { display:none;  } 
	</style>
	
</head>

<body>


  | baseMean | log2FoldChange | lfcSE | stat | pvalue | padj
-- | -- | -- | -- | -- | -- | --
TRINITY_DN476390_c0_g1_i1^BH049_ARATH | 0.545403040587589 | 3.04149676959377 | 3.97156564003663 | 0.765818079130556 | 0.443784555298429 | NA
TRINITY_DN3703_c0_g1_i1^ICE1_ARATH^HLH | 25.4298681836483 | 2.88274787535897 | 0.563532696897269 | 5.11549354852162 | 3.1292164339886E-07 | 2.95209471781164E-06
TRINITY_DN37974_c0_g1_i2^KINB2_ARATH^AMPK1_CBM | 43.6886237134121 | 5.00937921986817 | 0.834852328871958 | 6.00031771683117 | 1.96931814725472E-09 | 2.93449105933825E-08
TRINITY_DN9102_c0_g1_i3^FP1_MYTED | 9.85962384053658 | 7.16163007507952 | 3.55201694523972 | 2.01621506470493 | NA | NA
TRINITY_DN21808_c0_g1_i1^XRI1_ARATH | 11.4057151716744 | 2.32255154879515 | 0.714149430704949 | 3.25219267696191 | 0.00114518362763512 | 0.00411670510889106
TRINITY_DN403269_c0_g1_i1^SPT5H_DANRE | 1.02385472239335 | 3.68527918623357 | 3.94910801170011 | 0.933192805898221 | 0.350720428491039 | NA
TRINITY_DN167419_c0_g1_i1^MPDZ_RAT | 0.839386902726585 | 3.41324880762312 | 3.95749839568876 | 0.862476359141792 | 0.388425436895664 | NA
TRINITY_DN3534_c0_g1_i6^JAC1_ARATH | 90.7533585358057 | 2.69224395209417 | 0.60168861083911 | 4.47448049305702 | 7.65973187762513E-06 | 5.15179345611507E-05
TRINITY_DN244649_c0_g1_i1^GOLS1_ARATH | 140.825818963615 | 1.58060789980726 | 0.322043638162833 | 4.90805503510075 | 9.19840452704818E-07 | 7.78944498671904E-06
TRINITY_DN55051_c0_g1_i1^ALFC_SPIOL | 3.17724168640689 | 4.21999065385797 | 1.90372558225023 | 2.21670113235012 | 0.0266435213649284 | 0.0550545437596074
TRINITY_DN949572_c0_g1_i1^PAPS1_ARATH | 5.01184258412416 | 2.04105808154005 | 0.967907350107929 | 2.10873290848804 | 0.0349676425927578 | 0.0682239937693836
TRINITY_DN5676_c0_g1_i2^GOLS1_ARATH | 45.3413566997794 | 4.12113111995623 | 0.705948415450105 | 5.83772274257269 | 5.29191223827508E-09 | 7.25584072570148E-08
TRINITY_DN847189_c3_g1_i1^Y575_SYNY3^DUF2854 | 894.450802282964 | 3.05850385036275 | 0.315286475420349 | 9.70071375971669 | 2.99396764920369E-22 | 2.06540980308373E-20
TRINITY_DN9185_c0_g1_i2^ODP22_ARATH | 65.6470084293064 | 2.27101832900352 | 0.41549685209541 | 5.46578949407306 | 4.60850989033996E-08 | 5.22768053638792E-07
TRINITY_DN26586_c0_g1_i13^GID4_MOUSE | 0.458541020015179 | 2.44413869411353 | 3.89016928062143 | 0.628285947937744 | 0.529816635305815 | NA
TRINITY_DN35903_c0_g1_i2^GLUA_DICDI^Glyco_hydro_3 | 5.63692147777261 | 2.19642223177255 | 1.20337748962777 | 1.82521465683386 | 0.0679686428644591 | 0.117726361477985
TRINITY_DN47282_c0_g1_i1^CHD6_RAT^Chromo | 3.35754761090634 | 5.37618015404442 | 3.9202298507671 | 1.37139411685068 | NA | NA
TRINITY_DN10609_c0_g1_i3^CBSX1_ARATH^SUT21_ARATH^Sulfate_transp | 90.9954643132911 | 1.98678642733976 | 0.259742646054544 | 7.64905747099594 | 2.02457747191921E-14 | 6.55068178975832E-13
TRINITY_DN17005_c0_g1_i16^GLR22_ARATH^Peripla_BP_6 | 9.89806855021216 | 2.613620170122 | 0.711149862219975 | 3.67520308864737 | 0.000237660287258158 | 0.00106522480288737
TRINITY_DN547634_c1_g1_i1^PSAG_ARATH | 2.95271577913338 | 4.76144527108766 | 1.50999012066934 | 3.15329564472716 | 0.0016143821627572 | 0.00550888635454885
TRINITY_DN83479_c0_g1_i2^PSAG_ARATH | 1.03117959098969 | 3.12739578258459 | 2.4822287175723 | 1.25991443110983 | 0.207700232227196 | NA
TRINITY_DN392186_c0_g1_i1^RBL_STEHA | 2.20333812072147 | 4.8875383030121 | 2.24181253610817 | 2.18017261670638 | 0.0292446686042229 | 0.059179863940501
TRINITY_DN595419_c0_g1_i1^COG2_ARATH | 0.971579480667721 | 2.07576863207439 | 2.53195853041732 | 0.819827263020876 | 0.412314586784522 | NA
TRINITY_DN952521_c0_g1_i1^CAT2_CLOK5 | 0.687113466637308 | 3.07714773077969 | 3.97007011677754 | 0.775086494763819 | 0.438288551307343 | NA
TRINITY_DN707259_c0_g1_i1^CB24_TOBAC | 76.1437942980691 | 4.35959068174065 | 0.522071892006879 | 8.35055621359366 | 6.79422472953027E-17 | 2.91350711546945E-15
TRINITY_DN296917_c0_g1_i1^DXR_ARATH | 1.98842129341185 | 2.28450932853824 | 1.57969666797823 | 1.44616961904595 | 0.148129632732839 | 0.224697391136763
TRINITY_DN48938_c0_g1_i1^TIA1_HUMAN^RRM_1 | 1.32346912124486 | 3.98264307885317 | 3.94146637808475 | 1.01044705112731 | 0.312281155219958 | NA
TRINITY_DN7655_c0_g1_i1^PAM68_ARATH^DUF3464 | 438.772449053814 | 4.74994867284364 | 0.328657499395294 | 14.452579605161 | 2.4146997799978E-47 | 6.83801441412735E-45
TRINITY_DN76081_c0_g1_i1^CATA_SOLAP | 17.1660192194922 | 3.36492659889951 | 0.681937809291804 | 4.934359927035 | 8.04140307089959E-07 | 6.90858989886454E-06


</body>

</html>
   

in this result the pvalue > 0.05 were also listed.

so i wanted to know that which command will be usefull to select genes which satisfies the two comnditions(pvalue < 0.05 and logfc > 1.5)
Thank you

**Comment by mikelove** [comment]
Two things: 1) can you post instead to:

https://support.bioconductor.org

2) can you use an example that I can also reproduce, by making the dds with:

```
dds <- makeExampleDESeqDataSet()
```

Making an example involves posting the entire code so I can see the same error on my end.

**Comment by SREESHMARAJ659** [comment]
I am performing differential expression analysis with DESeq2. After running ```dds<- DESeq(dds)```  i wanted to retrive all the up and down regulated genes. i gave the conditionpvalue < 0.05 and log2FoldChnage > 1.5 for up regulated genes. But in the result file also include the genes which have pvalue > 0.05. iam pasting my example dataset here with the result. I wnted to know that which command will be helpfull here for retriving genes which satisfy the above mentioned two condition.

Thank you in advance. 
```r

> dds <- makeExampleDESeqDataSet()
> dds
class: DESeqDataSet 
dim: 1000 12 
metadata(1): version
assays(1): counts
rownames(1000): gene1 gene2 ... gene999 gene1000
rowData names(3): trueIntercept trueBeta trueDisp
colnames(12): sample1 sample2 ... sample11 sample12
colData names(1): condition
> dds <- DESeq(dds)
estimating size factors
estimating dispersions
gene-wise dispersion estimates
mean-dispersion relationship
final dispersion estimates
fitting model and testing
> res <- results(dds, alpha =0.05)
> res
log2 fold change (MLE): condition B vs A 
Wald test p-value: condition B vs A 
DataFrame with 1000 rows and 6 columns
          baseMean log2FoldChange     lfcSE       stat    pvalue      padj
         <numeric>      <numeric> <numeric>  <numeric> <numeric> <numeric>
gene1     12.61910      -0.320613  0.728490  -0.440107  0.659860  0.992529
gene2      6.01265      -1.391883  0.926580  -1.502172  0.133053  0.972932
gene3     71.48063      -0.723134  0.319153  -2.265794  0.023464  0.805855
gene4      7.56355      -0.347392  0.715907  -0.485248  0.627501  0.992529
gene5     11.86764       0.275620  0.634890   0.434123  0.664199  0.992529
...            ...            ...       ...        ...       ...       ...
gene996   27.95109     -0.4044216  0.420641 -0.9614415  0.336330  0.992529
gene997   41.27173     -0.0273015  0.341122 -0.0800344  0.936210  0.996243
gene998   32.97030      0.1177037  0.357531  0.3292127  0.741995  0.992529
gene999    2.85416     -0.4862333  1.009720 -0.4815524  0.630124  0.992529
gene1000   3.24778     -0.2205322  1.003172 -0.2198348  0.826000  0.992529
> RESULT <- res[which(res$pvalue<0.05) & abs(res$log2FoldChange > 1.5),]
Warning message:
In which(res$pvalue < 0.05) & abs(res$log2FoldChange > 1.5) :
  longer object length is not a multiple of shorter object length
> write.table(RESULT, file = "upregulated_test.txt")
> RESULT
log2 fold change (MLE): condition B vs A 
Wald test p-value: condition B vs A 
DataFrame with 30 rows and 6 columns
         baseMean log2FoldChange     lfcSE      stat     pvalue      padj
        <numeric>      <numeric> <numeric> <numeric>  <numeric> <numeric>
gene20    7.02072        1.88494  0.722398   2.60928 0.00907324  0.805855
gene45    4.76153        1.70103  0.877075   1.93943 0.05244909  0.851959
gene57    0.88648        3.34660  2.213826   1.51168 0.13061522  0.972932
gene74    1.27885        2.14873  1.632143   1.31651 0.18800332  0.992529
gene75    4.16297        1.79519  1.024415   1.75240 0.07970449  0.901962
...           ...            ...       ...       ...        ...       ...
gene868   1.34768        3.38540   1.50091   2.25557  0.0240976  0.805855
gene923   1.36849        1.68479   1.60413   1.05028  0.2935898  0.992529
gene932   6.63682        1.78308   0.86071   2.07164  0.0382986  0.851959
gene970   2.86467        1.79572   1.32983   1.35034  0.1769079  0.992529
gene977   4.02625        1.50587   1.01119   1.48920  0.1364334  0.974524

```

Iam also pasting the attaching the file which i created using above mentioned command.
 [1]: https://drive.google.com/file/d/16wlCco5epiqzf8JkRjjzQcVr0DVDdY-u/view?usp=sharing

**Comment by mikelove** [comment]
Notice the `Warning message`. This is because you need to wrap both logical vectors in the `which()`.

You have one logical with NA: `res$pvalue < 0.05`

And another one: `res$log2FoldChange > 1.5` (also see that you didn't wrap LFC in abs() but the logical, this is another issue besides the `which()` problem)

The correct line would be:

```
idx <- which( res$pvalue < 0.05 & abs( res$log2FoldChange ) > 1.5 )
res[idx,] # these are the rows you want
```
