### ISSUE TITLE
How did you decide the default significance level to be 0.1 in results()?

### ISSUE THREAD

**Issue by hchoiHiLung** [mikelove/DESeq2#79]
*This is not a question about the usage of DESeq2 but if you want me to post this on Bioconductor instead, I will do so.

Thanks very much for all the effort put on the package and your active responses to the community. I highly appreciate this.

It may sound a bit trivial but why did you choose 0.1 as the default significance level over 0.05 which is more conventional in biomedical field?
It seems to me in your original paper, https://genomebiology.biomedcentral.com/articles/10.1186/s13059-014-0550-8, you also used 0.1 as a cutoff.

I apologize if I have missed any well-known consensus/knowledge in bioinformatics but I am really eager to be enlightened.

**Comment by mikelove** [comment]
9/10 is often a reasonable hit rate for validation. These experiments are often used to generate hypotheses for follow-up experiments.
