### ISSUE TITLE
Installation error:

### ISSUE THREAD

**Issue by desmodus1984** [mikelove/DESeq2#81]
HI,
I tried installing DESeq2 using the instruction from Bioconductor, and I got the following error messages at the end:

ERROR: dependency ‘GenomeInfoDb’ is not available for package ‘GenomicRanges’
* removing ‘/home/juaguila/R/x86_64-pc-linux-gnu-library/4.3/GenomicRanges’
ERROR: dependencies ‘GenomicRanges’, ‘GenomeInfoDb’ are not available for package ‘SummarizedExperiment’
* removing ‘/home/juaguila/R/x86_64-pc-linux-gnu-library/4.3/SummarizedExperiment’
ERROR: dependencies ‘GenomicRanges’, ‘SummarizedExperiment’ are not available for package ‘DESeq2’
* removing ‘/home/juaguila/R/x86_64-pc-linux-gnu-library/4.3/DESeq2’
The downloaded source packages are in
	‘/tmp/RtmpKvEe8Q/downloaded_packages’
Installation paths not writeable, unable to update packages
  path: /usr/lib/R/library
  packages:
    boot, foreign, Matrix, nlme, spatial, survival
  path: /usr/lib/R/site-library
  packages:
    bench, BH, bit, blob, brew, broom, cachem, callr, caret, cba, checkmate,
    chron, classInt, cli, colorspace, commonmark, conquer, covr, cpp11, crayon,
    curl, CVST, data.table, DBI, DBItest, dbplyr, ddalpha, decor, deldir,
    DEoptimR, desc, devtools, digest, dimRed, dplyr, DT, e1071, earth,
    evaluate, fansi, farver, fastmap, filehash, FNN, Formula, fs, furrr,
    future, future.apply, gdata, generics, geometry, geosphere, gert, ggplot2,
    gh, gitcreds, globals, glue, gower, gplots, gtable, gtools, hexbin, highr,
    Hmisc, hms, htmlTable, htmltools, htmlwidgets, httpuv, httr, igraph,
    interp, ipred, isoband, jpeg, jsonlite, kernlab, knitr, ks, later,
    latticeExtra, lava, lifecycle, linprog, listenv, lme4, lobstr, logcondens,
    lpSolve, lubridate, lwgeom, magic, magrittr, mapproj, maps, maptools,
    markdown, MatrixModels, matrixStats, mclust, mda, mets, minqa, mlbench,
    mockr, modeldata, multcomp, mvtnorm, nloptr, openssl, palmerpenguins,
    parallelly, pillar, pkgbuild, pkgKitten, pkgload, plotmo, pls, plyr, png,
    polyclip, pracma, pROC, processx, prodlim, progressr, promises, proxy, ps,
    purrr, quantmod, quantreg, R.methodsS3, R.oo, ragg, raster, RColorBrewer,
    Rcpp, RcppArmadillo, RcppEigen, recipes, remotes, rgdal, rgl, rlang,
    rmarkdown, RMySQL, robustbase, roxygen2, RPostgreSQL, rprojroot, rsample,
    RSpectra, RSQLite, rstudioapi, rversions, s2, sandwich, sass, scales,
    setRNG, sf, sfsmisc, shiny, slider, sodium, sourcetools, sp, spatstat,
    spatstat.data, spatstat.geom, spatstat.linnet, spatstat.sparse,
    spatstat.utils, statmod, stringi, stringr, svglite, sys, terra, testthat,
    TH.data, tibble, tidyr, tidyselect, tikzDevice, timeDate, timereg,
    timeSeries, tinytex, tseries, units, usethis, utf8, vctrs, vdiffr, viridis,
    viridisLite, waldo, webfakes, whisker, withr, wk, wkutils, xfun, XML, xml2,
    xts, yaml, zip, zoo
Warning messages:
1: In install.packages(...) :
  installation of package ‘RCurl’ had non-zero exit status
2: In install.packages(...) :
  installation of package ‘GenomeInfoDb’ had non-zero exit status
3: In install.packages(...) :
  installation of package ‘GenomicRanges’ had non-zero exit status
4: In install.packages(...) :
  installation of package ‘SummarizedExperiment’ had non-zero exit status
5: In install.packages(...) :
  installation of package ‘DESeq2’ had non-zero exit status

> library(DESeq2)
Error in library("DESeq2") : there is no package called ‘DESeq2’

I work in a workstation with Linux Ubuntu 22.04.2 LTS

Thanks;

**Comment by mikelove** [comment]
Can we switch to Bioconductor support site instead for installation issues? So if you have follow up, post there please.

The above issue can be solved by installing GenomeInfoDb.

I also work on an Ubuntu machine, and I highly recommend Dirk's r2u solution:

https://eddelbuettel.github.io/r2u/
