### ISSUE TITLE
results.R help

### ISSUE THREAD

**Issue by biounix** [mikelove/DESeq2#85]
Hi,

The line 

_This argument is preserved for backward compatability, as now betaPrior=TRUE by default and the recommended pipeline is to generate shrunken MAP estimates using lfcShrink_

in results.R should probably read

_This argument is preserved for backward compatability, as now betaPrior=**FALSE** by default and the recommended pipeline is to generate shrunken MAP estimates using lfcShrink_

Thanks for this magnificent software.

**Comment by mikelove** [comment]
Thanks @biounix for the catch
