### ISSUE TITLE
save of DESeq2::DESeqDataSet

### ISSUE THREAD

**Issue by christophista** [mikelove/DESeq2#87]
Hello 

I have recently used your package in the targets pipeline and encountered a problem when the generated DESeq2::DESeqDataSet object when saved with qs::qsave. It seems the slot @design, which saves the formula for the comparison (and the environment) are either too large or have any special object/cyclic dependency that causes qsave to fail and produce file sizes of several GB (up to 60). 
Please find the steps underneath. 

A solution that seems to have worked for me is to remove the environment (e.g., set @design to a string)

Thus, my question:
While it is not a problem of your package, I was wondering the following:
Is this design slot and the formula important in subsequent data analysis steps? Or is the environment of the formula important in these? Is it save to remove it? 

Thank you in advance
Best regards, christoph

Steps: 
1) create DESeq2::DESeqDataSet object with DESeq2::DESeq(dds, test = "Wald", fitType = "local") - no problems
2) check object size in memory: around 600MB - no problems
3) save object with saveRDS, around 1GB file size - no problems
4) save object with qs::qsave - problem, 60GB file size and R crashes

**Comment by luciorq** [comment]
The main question here is, do you really need to use `qs` for serialization of the object, are you loading this object in another languages?
Just save it with other strategies, like `readr::write_rds()`.

Now, talking specifically about `targets`, it is not a good idea to write different targets for each step that call functions that just add slots to an S4 object. It will always try to hash/cache the state of the whole object in each step.

I foresee that `qs::save` would have this problem with several other Bioconductor S4 objects.

**Comment by christophista** [comment]
Thank you for your answer. 

There is some exchange with python code via the qs serialization. I will look into the RDS serialization and try to switch. 
Thank you for the hint that there might also be problems with other Bioconductor packages!

**Comment by mikelove** [comment]
Just so you are aware, another issue with saving R objects that contain formula, which has come up before on the support site:

```
> x <- rnorm(1e7)
> f <- formula(~x)
> save(f, file="test.rda")
> myfunction <- function() { x <- rnorm(1e7); formula(~x) }
> f2 <- myfunction()
> save(f2, file="test2.rda")
```

```
total 163976
-rw-r--r--  1 milove  staff   114B Oct  6 06:46 test.rda
-rw-r--r--  1 milove  staff    73M Oct  6 06:47 test2.rda
```

If you run `DESeqDataSet` construction inside of a function, it will save everything in the environment. This is a property of R's `formula` and I haven't ever found a way to prevent this. It won't happen if `formula` is called in the global environment though. So if you run `DESeqDataSet` construction in the global environment it won't accumulate all this data.

**Comment by christophista** [comment]
Thank you also for the example. I guess this is in fact than exactly what caused the problem for me. 
In fact, the DESeqDataSet constrution is called in nested functions, but this I cannot change easily. 

Thank you! Your help and explanations are much appreciated!

**Comment by mikelove** [comment]
I tried for a long time to come up with a solution but it's apparently un-modifiable behavior of this base R function to do this.

It only affects users who are creating objects inside of functions, so most users aren't affected.

You can delete large objects from the environment (inside the function) after you create `dds` but you can't delete the `dds` itself, obviously. Inception!

**Comment by mikelove** [comment]
Oh yeah I did solve this eventually:

You can provide the output of model.matrix() to design, instead of a formula. This avoids the issue I believe.
