### ISSUE TITLE
DESeq2 for single-cell pseudobulk: top genes have low expression

### ISSUE THREAD

**Issue by DaianeH** [mikelove/DESeq2#88]
(posting this issue here because was unable to do so on Bioconductor support site)

I'm using pseudobulk on scRNA-seq data from a Seurat object to compare two groups of cancer patients (with TP53 mutation vs wild-type) using Deseq2.

The most differentially expressed gene is LRP6, with a log2FoldChange of 7 and padj=6e-13. Here’s the Deseq2 plot of counts aggregated per sample as pseudo-bulk (each circle is a sample), where we can see that definitely this gene seems to be not expressed in WT, but expressed in MUT:

![LRP6](https://github.com/thelovelab/DESeq2/assets/2428375/7524de66-12ea-47c6-b384-5f0d87737ff0)

However, when I use Seurat VlnPlot function (with pt.size=0) to plot the expression of this gene on the Seurat object, I don’t see much expression of this gene, most cells have zero expression which is not even enough to form a violin:

![LRP6_violin](https://github.com/thelovelab/DESeq2/assets/2428375/0cb7df19-e0fe-46dd-8413-cca127643e28)

There's definitely some cells expressing this gene, more so in MUT, but not enough to form a violin.
So I wonder, is this gene really differentially expressed? Is it expressed enough to be considered biologically important?
For comparison, this is how a positive control should look like, a gene that is definitely expressed, differentially expressed, and biologically important:
 
![IFITM3](https://github.com/thelovelab/DESeq2/assets/2428375/d52bb85a-e3ca-42db-8064-adffbc3b498e)

Thank you in advance,

**Comment by mikelove** [comment]
Is Seurat showing per cell expression?

Then that’s not a problem at all. The pseudo bulk is showing the across sample difference that it sounds like you care about.

**Comment by mikelove** [comment]
Closing for now. Folks may have more input on biostars or support.bioconductor.org
