### ISSUE TITLE
DESeq2 Summarized Experiment Unable to Install

### ISSUE THREAD

**Issue by emgreen1014** [mikelove/DESeq2#89]
I have been using DESeq2 now for several months and my code has been working just fine for my analysis. However, today I was unable to load the DESeq package. It appears the issue is due to the inability to install "SummarizedExperiments", "SparseArray", and "DelayedArray", although I get the same error when I try to install these dependent packages. See code and error messages below:

> library("DESeq2")
Error: package ‘SummarizedExperiment’ required by ‘DESeq2’ could not be found
> BiocManager::install("SummarizedExperiment")
'getOption("repos")' replaces Bioconductor standard repositories, see 'help("repositories", package = "BiocManager")' for
details.
Replacement repositories:
    CRAN: https://cran.rstudio.com/
Bioconductor version 3.18 (BiocManager 1.30.22), R 4.3.1 (2023-06-16)
Installing package(s) 'SummarizedExperiment'
also installing the dependencies ‘SparseArray’, ‘DelayedArray’

Packages which are only available in source form, and may need compilation of C/C++/Fortran: ‘SparseArray’
  ‘DelayedArray’
Do you want to attempt to install these from sources? (Yes/no/cancel) Yes
installing the source packages ‘SparseArray’, ‘DelayedArray’, ‘SummarizedExperiment’

trying URL 'https://bioconductor.org/packages/3.18/bioc/src/contrib/SparseArray_1.2.1.tar.gz'
Content type 'application/x-gzip' length 366888 bytes (358 KB)
==================================================
downloaded 358 KB

trying URL 'https://bioconductor.org/packages/3.18/bioc/src/contrib/DelayedArray_0.28.0.tar.gz'
Content type 'application/x-gzip' length 624166 bytes (609 KB)
==================================================
downloaded 609 KB

trying URL 'https://bioconductor.org/packages/3.18/bioc/src/contrib/SummarizedExperiment_1.32.0.tar.gz'
Content type 'application/x-gzip' length 686052 bytes (669 KB)
==================================================
downloaded 669 KB

* installing *source* package ‘SparseArray’ ...
** using staged installation
** libs
xcrun: error: unable to load libxcrun (dlopen(/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib, 0x0005): tried: '/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need '')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib' (no such file), '/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need ''))).
Warning in system(paste(MAKE, p1(paste("-f", shQuote(makefiles))), "compilers"),  :
  running command 'make -f '/Library/Frameworks/R.framework/Resources/etc/Makeconf' -f '/Library/Frameworks/R.framework/Resources/share/make/shlib.mk' compilers' had status 1
sh: --version: command not found
Warning in system2("xcrun", "--show-sdk-path", TRUE, TRUE) :
  running command ''xcrun' --show-sdk-path 2>&1' had status 1
using SDK: ‘NA’
xcrun: error: unable to load libxcrun (dlopen(/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib, 0x0005): tried: '/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need '')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib' (no such file), '/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need ''))).
ERROR: compilation failed for package ‘SparseArray’
* removing ‘/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/SparseArray’
ERROR: dependency ‘SparseArray’ is not available for package ‘DelayedArray’
* removing ‘/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/DelayedArray’
ERROR: dependency ‘DelayedArray’ is not available for package ‘SummarizedExperiment’
* removing ‘/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/SummarizedExperiment’

The downloaded source packages are in
	‘/private/var/folders/vw/mvbj3b_x5lz5yfmj57wr0x000000gn/T/RtmpuVHSkY/downloaded_packages’
Old packages: 'graphlayouts', 'lifecycle', 'lintr', 'matrixStats', 'rlang', 'rprojroot', 'RSQLite'
Update all/some/none? [a/s/n]: 
a
trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.3/graphlayouts_1.0.1.tgz'
Content type 'application/x-gzip' length 4504877 bytes (4.3 MB)
==================================================
downloaded 4.3 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.3/lifecycle_1.0.3.tgz'
Content type 'application/x-gzip' length 123639 bytes (120 KB)
==================================================
downloaded 120 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.3/lintr_3.1.0.tgz'
Content type 'application/x-gzip' length 1202163 bytes (1.1 MB)
==================================================
downloaded 1.1 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.3/matrixStats_1.0.0.tgz'
Content type 'application/x-gzip' length 614723 bytes (600 KB)
==================================================
downloaded 600 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.3/rlang_1.1.1.tgz'
Content type 'application/x-gzip' length 1877647 bytes (1.8 MB)
==================================================
downloaded 1.8 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.3/rprojroot_2.0.3.tgz'
Content type 'application/x-gzip' length 100727 bytes (98 KB)
==================================================
downloaded 98 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.3/RSQLite_2.3.2.tgz'
Content type 'application/x-gzip' length 4240223 bytes (4.0 MB)
==================================================
downloaded 4.0 MB

The downloaded binary packages are in
	/var/folders/vw/mvbj3b_x5lz5yfmj57wr0x000000gn/T//RtmpuVHSkY/downloaded_packages
Warning messages:
1: In install.packages(...) :
  installation of package ‘SparseArray’ had non-zero exit status
2: In install.packages(...) :
  installation of package ‘DelayedArray’ had non-zero exit status
3: In install.packages(...) :
  installation of package ‘SummarizedExperiment’ had non-zero exit status
> if (!require("BiocManager", quietly = TRUE))
+   install.packages("SparseArray")
Bioconductor version 3.18 (BiocManager 1.30.22), R 4.3.1 (2023-06-16)
>   BiocManager::install("SparseArray")
'getOption("repos")' replaces Bioconductor standard repositories, see 'help("repositories", package =
"BiocManager")' for details.
Replacement repositories:
    CRAN: https://cran.rstudio.com/
Bioconductor version 3.18 (BiocManager 1.30.22), R 4.3.1 (2023-06-16)
Installing package(s) 'SparseArray'
Package which is only available in source form, and may need compilation of C/C++/Fortran:
  ‘SparseArray’
Do you want to attempt to install these from sources? (Yes/no/cancel) yes
installing the source package ‘SparseArray’

trying URL 'https://bioconductor.org/packages/3.18/bioc/src/contrib/SparseArray_1.2.1.tar.gz'
Content type 'application/x-gzip' length 366888 bytes (358 KB)
==================================================
downloaded 358 KB

* installing *source* package ‘SparseArray’ ...
** using staged installation
** libs
xcrun: error: unable to load libxcrun (dlopen(/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib, 0x0005): tried: '/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need '')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib' (no such file), '/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need ''))).
Warning in system(paste(MAKE, p1(paste("-f", shQuote(makefiles))), "compilers"),  :
  running command 'make -f '/Library/Frameworks/R.framework/Resources/etc/Makeconf' -f '/Library/Frameworks/R.framework/Resources/share/make/shlib.mk' compilers' had status 1
sh: --version: command not found
Warning in system2("xcrun", "--show-sdk-path", TRUE, TRUE) :
  running command ''xcrun' --show-sdk-path 2>&1' had status 1
using SDK: ‘NA’
xcrun: error: unable to load libxcrun (dlopen(/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib, 0x0005): tried: '/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need '')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib' (no such file), '/Library/Developer/CommandLineTools/usr/lib/libxcrun.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need ''))).
ERROR: compilation failed for package ‘SparseArray’
* removing ‘/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/SparseArray’

The downloaded source packages are in
	‘/private/var/folders/vw/mvbj3b_x5lz5yfmj57wr0x000000gn/T/RtmpuVHSkY/downloaded_packages’
Old packages: 'graphlayouts', 'lifecycle', 'lintr', 'matrixStats', 'rlang', 'rprojroot', 'RSQLite'
Update all/some/none? [a/s/n]: 
a
trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.3/graphlayouts_1.0.1.tgz'
Content type 'application/x-gzip' length 4504877 bytes (4.3 MB)
==================================================
downloaded 4.3 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.3/lifecycle_1.0.3.tgz'
Content type 'application/x-gzip' length 123639 bytes (120 KB)
==================================================
downloaded 120 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.3/lintr_3.1.0.tgz'
Content type 'application/x-gzip' length 1202163 bytes (1.1 MB)
==================================================
downloaded 1.1 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.3/matrixStats_1.0.0.tgz'
Content type 'application/x-gzip' length 614723 bytes (600 KB)
==================================================
downloaded 600 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.3/rlang_1.1.1.tgz'
Content type 'application/x-gzip' length 1877647 bytes (1.8 MB)
==================================================
downloaded 1.8 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.3/rprojroot_2.0.3.tgz'
Content type 'application/x-gzip' length 100727 bytes (98 KB)
==================================================
downloaded 98 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.3/RSQLite_2.3.2.tgz'
Content type 'application/x-gzip' length 4240223 bytes (4.0 MB)
==================================================
downloaded 4.0 MB

The downloaded binary packages are in
	/var/folders/vw/mvbj3b_x5lz5yfmj57wr0x000000gn/T//RtmpuVHSkY/downloaded_packages
Warning message:
In install.packages(...) :
  installation of package ‘SparseArray’ had non-zero exit status

**Comment by mikelove** [comment]
going to continue on your support site post

https://support.bioconductor.org/p/9155057/
