### ISSUE TITLE
`results` function fails for interaction designs (v1.20)

### ISSUE THREAD

**Issue by vivekbhr** [mikelove/DESeq2#9]
Hi Mike 

I looked like a bug, therefore, I am reporting here. The `results` command fails for the designs with interactions, complaining that the `betaPrior` slot is not full in the `dds` object (which is always set to FALSE for interaction designs anyway).

R version : 3.5.0
bioc version : 3.6.0
DESeq2 version : 1.20

It works with version `1.18` on the same data

**Comment by mikelove** [comment]
Can you post this to the support site with a small example?

**Comment by elenichri** [comment]
Hello,
I am interested in this question. I have an interaction term in my design and results runs ok on R. 3.5.0 bioc 3.6.0 and DESeq2 1.2. Could you please provide a link to the support site?

Thank you very much!

**Comment by mikelove** [comment]
support.bioconductor.org
