### ISSUE TITLE
Add possibility to simulate data

### ISSUE THREAD

**Issue by frederikziebell** [mikelove/DESeq2#90]
Hi Mike,

I was wondering if you'd find it helpful to add the posibility to simulate new data based on an already fitted model. This would allow to investigate if the design chosen captures the relevant biology in the data. Here's a rough example

```r
library("airway")
library("DESeq2")
library("tidyverse")

# return genes x samples matrix of expectations of the NB model 
expectations <- function(dds){
  X <- model.matrix(design(dds), data = colData(dds))
  beta <- coefficients(dds)
  size_factor <- colData(dds)$sizeFactor
  Y_hat <- 2^tcrossprod(beta, X)
  sweep(Y_hat, 2, size_factor, FUN="*")
}

simulate <- function(dds){
    
   mu <- expectations(dds)
   dispersion <- mcols(dds)$dispersion
   
   counts <- matrix(
    rnbinom(n = length(mu), mu = mu, size = 1/dispersion), 
    ncol = ncol(mu), nrow = nrow(mu),
    dimnames = list(rownames(dds), colData(dds)$colname)
  )
  mode(counts) <- "integer"
  
  # remove old diff. testing results from dds
  base_mean_col <- which(colnames(rowData(dds)) == "baseMean")
  rowData(dds)[,base_mean_col:ncol(rowData(dds))] <- NULL
  colData(dds)$sizeFactor <- NULL
  
  DESeqDataSet(
    se = SummarizedExperiment(
      assays = list(counts=counts),
      rowData = rowData(dds),
      colData = colData(dds)
    ),
    design = design(dds),
  )
}

data(airway)
dds <- DESeqDataSet(airway, ~cell+dex)
dds <- dds[rowSums(counts(dds) >= 5) >= 3, ]
dds <- DESeq(dds)

set.seed(1)
dds_sim <- simulate(dds)

vsd <- vst(dds)
vsd_sim <- vst(dds_sim)

plotPCA(vsd, intgroup="cell") + labs(title = "observed")
plotPCA(vsd_sim, intgroup="cell") + labs(title = "simulated", subtitle = "design: ~ cell + dex")

# simulate with incomplete design
dds2 <- dds
design(dds2) <- ~ dex
dds2 <- DESeq(dds2)
dds2_sim <- simulate(dds2)
vsd2_sim <- vst(dds2_sim)
plotPCA(vsd2_sim, intgroup="cell") + labs(title = "simulated", subtitle = "design: ~ dex")
```

![image](https://github.com/thelovelab/DESeq2/assets/28304028/c669c3ac-b5e8-49d1-9b27-08315d4b7b22)
![image](https://github.com/thelovelab/DESeq2/assets/28304028/d1f6bb1a-b70e-4145-b504-39148f806e79)
![image](https://github.com/thelovelab/DESeq2/assets/28304028/e9d8eaca-ec2b-4c44-a0d2-14201113b56c)

Of course there are some edge-cases I'm not covering, e.g. if a gene is all zero and coefficients are NA, so it's probably some additional work to cover those.

**Comment by mikelove** [comment]
I like this as a Rmd maybe? Or a standalone package, e.g. simulate DESeq2 from fitted model.

Note also:

https://bioconductor.org/packages/release/bioc/html/countsimQC.html 

from Charlotte Soneson which would let you compare if it is a good match.

I wonder if it's better to use the shrunken LFC as these are closer (in terms of total squared error) to the real LFC than the MLE.

**Comment by mikelove** [comment]
Closing for now but feel free to discuss further here or on Bioc slack
