### ISSUE TITLE
How to export the normalized matrix of RNA-seq?

### ISSUE THREAD

**Issue by hyjforesight** [mikelove/DESeq2#92]
Hello Dr Love,
Thank you for developing this amazing package.
I understand that we can export the normalized matrix by
```R
dds <- estimateSizeFactors(dds)
counts(dds, normalized=TRUE)
```

However, as the vignette explains, downstream processing generally requires more advanced normalization, to account for the heteroscedasticity of the counts. This is often done by rlog or vst.
I'm going to use the normalized matrix for downstream GESA. Could you please tell me which matrix is better for GSEA, the former one (counts(dds, normalized=TRUE)) or the vst-transformed one? If the vst-transformed one is prefered, could you please share the codes for exporting this matrix?

Thank you!
Best,
Yuanjian

**Comment by hyjforesight** [comment]
I found it. Vst-transformed matrix is in assay(vsd).
This question can be simplified. Which matrix is better for GSEA, the former one (counts(dds, normalized=TRUE)) or the vst-transformed one?
Thank you!

**Comment by mikelove** [comment]
I can’t answer that without knowing the tool.

You may want to post on biostars or search the Bioc support site for relevant questions.
