### ISSUE TITLE
how to get a gtf file when using tximprot for an organism without genome sequence and annotation file

### ISSUE THREAD

**Issue by luwd401** [mikelove/DESeq2#93]
hi, @mikelove

I met a problem when I perform RNA-seq analysis for differential expression analysis with DESeq2.
The genome of the species I am studying has not been sequenced. For transcriptome analysis without a reference genome, preparing the tx2gene file in tximport for DESeq2 analysis requires first to obtain a GTF file which contains transcriptome annotation information. For species without a reference genome, there are neither genome sequences nor gene annotation GTF files. How to obtain the GTF files? Can I used the output of transcripts assembler (not with trinity, because the assembly results indicated that it is not the best choice) to obtain my gtf file? If possible, how can I do with a transcript.fasta file? 

Best wishes!
Weidong Lu

**Comment by mikelove** [comment]
This is more of an bioinformatics analysis Q than code base Q. Would you mind posting to Bioc support site and tag with DESeq2?
