### ISSUE TITLE
limma::removeBatchEffect section of tutorial not working properly?

### ISSUE THREAD

**Issue by andrebolerbarros** [mikelove/DESeq2#94]
Hi everyone,

This is not any issue with the package, it's only concerning the tutorial https://www.bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html

I was checking the walkthrough of "Analysing RNA-seq data with DESeq2" (amazing job, by the way!) and I found the section on "Why after VST are there still batches in the PCA plot?" very useful. However, I was trying to adapt the code snippet to my own code but it wasn't working. 

When checking the info about the function itself (https://rdrr.io/bioc/limma/man/removeBatchEffect.html), I found that the `design` slot is for "design matrix relating to treatment conditions to be preserved, usually the design matrix with all experimental factors other than the batch effects." I think, in the given example, the design matrix is causing some issues with the code and might not be required at all.

Keep up the amazing work!

André

**Comment by mikelove** [comment]
Do you get an error?

The code is intended for a user that has a condition and a batch variable.

**Comment by andrebolerbarros** [comment]
It was my problem, using the same variable in condition and in batch sections. I'm going to close this, so sorry for this mistake!

**Comment by mikelove** [comment]
No problem :)
