### ISSUE TITLE
A question about whether to add 1 to the raw count before Deseq2 analysis

### ISSUE THREAD

**Issue by jessicaliu09** [mikelove/DESeq2#98]
Hi, 

We are using Deseq2 for miRNA analysis.

After filter miRNA by 
keep <- rowSums( counts(dds) >= 10 ) >= smallest_sample_size
dds <- dds[keep,]

When I run the DESeq() on my data, there is no significant miRNA  after Padj < 0.05. 

A colleague of mine said they added 1 count to the raw count, turned independent filtering off, and get 59 genes as significant, so including these lowly expressed miRNA. From my understanding, Deseq2 does not use log2 transformation (needed +1 for the zero count miRNA), we should just use raw count and deseq2 its self can handle the zero count miRNA .  

However, because the data miRNA has many zero count, but we still want to significant results, do u think we can still use raw count +1 and filter significant miRNA by baseMean > 10?  What else can we do? Any extra filtering steps we should do? Any recommendations?

Thanks!

**Comment by mikelove** [comment]
We do not recommend to add 1s, this will disturb the statistics. You can google the support site for posts on this topic.
