### ISSUE TITLE
How can I install DESeq2 with Bioconductor version 3.19 (BiocManager 1.30.22), R 4.4.0 (2024-04-24)

### ISSUE THREAD

**Issue by monis4567** [mikelove/DESeq2#99]
I appear unable to install DESeq2 with Bioconductor version 3.19 (BiocManager 1.30.22), R 4.4.0 (2024-04-24). I think it relates to the packages 'littler'. But I am not sure why.

**Comment by mikelove** [comment]
Could you post on support.bioconductor.org with full details?
